//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string FacultyId { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Address { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
